name: Checkstyle on branch
on: [push]
jobs:
  checkstyle:
    name: Run for checkstyle
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'adopt'
      - name: Run checkstyle
        run: mvn checkstyle:check
